# start from base
FROM arm64v8/python:3

LABEL maintainer="Ross Ellerington <ross@ellerington.net>"
# RUN apt-get update -y && \
#     apt-get install -y python-pip python-dev

# We copy just the requirements.txt first to leverage Docker cache

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

#CMD [ "python", "./app.py" ]